# Custom Language File for Launcher Customizer

[ejs.app]
title = "Station48 Launcher"

[ejs.landing]
mediaGitHubURL = "https://station48.xyz"
mediaXURL = ""
mediaInstagramURL = ""
mediaYouTubeURL = ""
mediaDiscordURL = "https://discord.gg/Hq5j3WhX9b"

[ejs.settings]
sourceGithubLink = "https://github.com/Station48XYZ/Station48Launcher"
supportLink = "https://github.com/Station48XYZ/Station48Launcher/issues"

[ejs.welcome]
welcomeHeader = "Welcome to Station48"
welcomeDescription = "Station48 is a all Inclusive and Welcoming Community Minecraft Server for all Players, Devs and non-devs alike! We are a community of developers (Mostly Astro Devs), builders, and players who love to relax, create, and play Minecraft together."
welcomeDescCTA = "You are just a few clicks away from getting started on your Station48 journey!"
