# Custom Language File for Launcher Customizer

[ejs.app]
title = "TempusMMO Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/TempusMMORPG/TempusLauncher"
mediaXURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/ky8zPFk"

[ejs.settings]
sourceGithubLink = "https://github.com/TempusMMORPG/TempusLauncher"
supportLink = "https://github.com/TempusMMORPG/TempusLauncher/issues"

[ejs.welcome]
welcomeHeader = "Welcome to TempusMMORPG"
welcomeDescription = "TempusMMO is an open-world, adventure roleplay server with the aiming to be a fully functioning Cobblemon MMO based on the Pokemon Anime, in a completely new region!"
welcomeDescCTA = "You are just a few clicks away from entering the world of Tempus."
